### PR TITLE
allow php8.0

### PR DESCRIPTION
**Pull request by alexandrbarabolia**
Hello, please accept pr.

### CODE REVIEW

**Comment by alexandrbarabolia** [comment]
@Velhron, please check.

**Comment by Velhron** [comment]
@alexandrbarabolia, hello. I'll check everything today. Thanks!

**Comment by alexandrbarabolia** [comment]
@Velhron, please make new release. Thank.

**Comment by Velhron** [comment]
@alexandrbarabolia, done!

**Pull request merged**
